services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    restart: unless-stopped

  api:
    build:
      context: ./api-py
      dockerfile: Dockerfile
    ports:
      - "5050:5000"
    env_file:
      - ./api-py/.env
    volumes:
      - ./api-py:/app
    networks:
      - app-network
    depends_on:
      psql:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./api-py
          target: /app
          ignore:
            - __pycache__/
            - .venv/

  redis:
    image: redis:7
    ports:
      - "6279:6379"
    networks:
      - app-network

  psql:
    image: postgres:latest
    env_file:
      - ./api-py/.env
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bluesky"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  psql_volume:

networks:
  app-network:
    driver: bridge
