services:
  redis:
    image: redis:7
    ports:
      - "6279:6379"
    networks:
      - app-network

  psql:
    image: postgres:latest
    env_file: .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  psql_volume:

networks:
  app-network:
    driver: bridge
