global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Internal port within container

  - job_name: 'bluesky-api'
    static_configs:
      - targets: ['api:5000']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Worker metrics are tracked via API since worker doesn't expose HTTP endpoint
  # RQ job metrics are collected through the API's /metrics endpoint