global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bluesky-api'
    static_configs:
      - targets: ['api:5000']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  - job_name: 'bluesky-worker'
    static_configs:
      - targets: ['worker:8000']  # We'll add metrics endpoint to worker later
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 10s